Gemfile.lock, index.html
And the json version in gem lock
=> archive links

_config.yml, _includes/head.html, melbourne/index.html, sydney/index.html
- Use html meta tag as well as Open Graph tags
- Update base site description tag
- Add tags specific to each city
=> Update meta description tags

_sass/_layout.scss, js/main.js
Get rid of the jump when header detaches from page layout and becomes fixed
=> Fix jump during scroll in about/sponsor

about.html, sponsor.html
- Update prospectus links and move up page for visibility 😍 
- Correct typos
=> Update sponsor page

next.config.js, package-lock.json, package.json
- Updated to Next 8.0.1
- Removed config stuff that is no longer needed from v8 onwards (see [this](https://github.com/zeit/next.js/issues/5750#issuecomment-451607604) for more info about the original workaround)
=> Updated to Next 8

components/schedule/schedule.tsx, content/2019/schedule.json
Since NextJS is server-rendered, moment didn't understand the schedule was in Aus time, that's been fixed now :)
=> Fixed schedule timezone

sections/melbourne-2019/event-schedule/event-schedule.tsx
back again with the moment ssr fix
=> Fix moment ssr on day selectors

components/table/column/column.scss, components/table/column/column.tsx, components/table/table.tsx, content/2020/sponsorship-packages.json, package-lock.json, pages/sponsorship/index.tsx
- defined structure for JSON
- added column component with header/footer styling and props
- added basic table component
=> added columns and basic table

sections/sponsor-prompt/sponsor-prompt.tsx
and prettier formatting changes
=> Updated prospectus link to 2020 version

components/footer/footer.tsx, pages/index.tsx, sections/hero/hero.tsx
=> Update homepage with 2020 teaser, remove 2019 stuff

components/footer/footer.scss, components/footer/footer.tsx
=> Footer Makeover 💄✨

pages/sponsorship/index.tsx
=> changed sponsorship page title to 2020

components/alert/alert.scss, components/alert/alert.tsx, package-lock.json, pages/index.tsx, pages/sponsorship/index.tsx, sections/hero/hero.tsx, sections/sponsor-info/sponsor-info.tsx
=> Add alert message on website

content/faqs.json, layouts/page/page.tsx, pages/index.tsx, pages/sponsorship/index.tsx, sections/about-us/about-us.tsx, sections/hero/hero.tsx, sections/sponsor-info/sponsor-info.tsx
removed covid alert
added 2021 dates to homepage and sponsorship page
changed occurrences of "24 hours" to "46 hours"
=> added 2021 dates

next.config.js, package-lock.json, package.json
- Updated to Next.js 10
- Added redirects:
- `/mentor` -> Mentor Form
- `/mentor-info` -> Mentor Info Pack
=> Next.js 10, added mentor form redirect

next.config.js
added mentor-brief redirect which also points to mentor-info
=> Added mentor-brief redirect

components/schedule/schedule-item/schedule-item.module.scss, components/schedule/schedule-item/schedule-item.tsx, content/2019/schedule.json, pages/_document.tsx, pages/index.tsx, sections/melbourne-2019/event-schedule/event-schedule.module.scss, sections/melbourne-2019/event-schedule/event-schedule.tsx, sections/melbourne-2019/sponsors/sponsors.module.scss
Also cleaned up a couple of things
=> Added 2021 schedule

components/schedule/schedule.tsx, content/2021/schedule.json
tldr: page gets rendered in the US, "active" schedule item isn't accurate, wasn't updating client-side. now it should update client-side
=> Fixed time bug

content/perks.json, sections/brand-hero/brand-hero.module.scss, sections/sponsor-hero/sponsor-hero.tsx
also changed some sponsorship content
=> Fixed mobile hero

components/footer/footer.tsx, next.config.js, package-lock.json, package.json, pages/rules/index.mdx, pages/rules/rules.md, pages/rules/rules.module.scss
Installed next mdx and loader (https://mdxjs.com/getting-started/next). Created rules page by importing rules.md from https://github.com/unihackhq/rules/blob/master/rules.md and rendering in the mdx file. This is my first time using nextjs so let me know if I have done something wrong!
=> Create rules page using mdx

components/footer/footer.tsx, content/pages/code-of-conduct.mdx, next.config.js, pages/conduct/conduct.module.scss, pages/conduct/index.tsx
Added code of conduct page, route and link in footer. Let me know if any changes needed!
=> Add Code of Conduct Page

README.md
Updated readme file with image component
=> update readme to include image component
